kind: ConfigMap
apiVersion: v1
metadata:
  name: cronjob1-cm
  namespace: cron-jobs
data:
  RECEIVER_EMAIL: "somedefault@mail.com"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob1
  namespace: cron-jobs
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob1
            image: REPLACEWITHYOURACR.azurecr.io/cronjob1:latest
            env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "QA"
            - name: "DOTNET_ENVIRONMENT"
              value: "QA"
            - name: "RECEIVER_EMAIL"
              valueFrom:
                configMapKeyRef:
                  name: cronjob1-cm
                  key: RECEIVER_EMAIL
          restartPolicy: OnFailure
